[project]
name = "customtimetable"
dynamic = ["version"]
license = "MIT"
dependencies = [
    "apache-airflow",
    "flask"
]

[project.entry-points."airflow.plugins"]
my_plugin = "my_package.my_plugin:MyAirflowPlugin"